[package]
name = "templated"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tera = { git = "https://github.com/Anti-Raid/tera" }
darklua = { version = "0.13" }
rand = { version = "0.8", features = [] }